### ISSUE TITLE
Delete components from library

### ISSUE THREAD

**Issue by lauratmercer** [LitSignal/publicissues#35]
I linked to the same practice bulletin twice - one in its HTML link and one in the PDF link...  Though I was able to rename one of the links, I was unable to delete the duplicate.

**Comment by brianmacarthur** [comment]
That is a good point. There should be a delete from library and imports feature. There should also be a merge capability when two different Litsignal components refer to the same entity. I will add these as new issues. Thanks for the report!

**Comment by brianmacarthur** [comment]
I am going to close this issue and fold it into the revised concept of the Litsignal library.
